# vim: set ts=2 et:
# deployer bundle for stable charms
# UOSCI relies on this for OS-on-OS deployment testing
openstack-services:
  services:
    mysql:
      branch: lp:charms/trusty/mysql
      constraints: mem=1G
      options:
        dataset-size: 50%
    rabbitmq-server:
      branch: lp:charms/trusty/rabbitmq-server
      constraints: mem=1G
    ceph:
      branch: lp:charms/trusty/ceph
      num_units: 3
      constraints: mem=1G
      options:
        monitor-count: 3
        fsid: 6547bd3e-1397-11e2-82e5-53567c8d32dc
        monitor-secret: AQCXrnZQwI7KGBAAiPofmKEXKxu5bUzoYLVkbQ==
        osd-devices: /dev/vdb
        osd-reformat: "yes"
        ephemeral-unmount: /mnt
    keystone:
      branch: lp:charms/trusty/keystone
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      branch: lp:charms/trusty/openstack-dashboard
      constraints: mem=1G
    nova-compute:
      branch: lp:charms/trusty/nova-compute
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
    nova-cloud-controller:
      branch: lp:charms/trusty/nova-cloud-controller
      constraints: mem=1G
      options:
        network-manager: Neutron
        quantum-security-groups: "yes"
    neutron-gateway:
      branch: lp:charms/trusty/quantum-gateway
      constraints: mem=1G
      options:
        instance-mtu: 1300
    cinder:
      branch: lp:charms/trusty/cinder
      options:
        block-device: "None"
        glance-api-version: 2
      constraints": mem=1G
    cinder-ceph:
      branch: lp:charms/trusty/cinder-ceph
    glance:
      branch: lp:charms/trusty/glance
      constraints: mem=1G
    swift-proxy:
      branch: lp:charms/trusty/swift-proxy
      constraints: mem=1G
      options:
        zone-assignment: manual
        replicas: 3
        swift-hash: fdfef9d4-8b06-11e2-8ac0-531c923c8fae
    swift-storage-z1:
      branch: lp:charms/trusty/swift-storage
      constraints: mem=1G
      options:
        zone: 1
        block-device: vdb
        overwrite: "true"
    swift-storage-z2:
      branch: lp:charms/trusty/swift-storage
      constraints: mem=1G
      options:
        zone: 2
        block-device: vdb
        overwrite: "true"
    swift-storage-z3:
      branch: lp:charms/trusty/swift-storage
      constraints: mem=1G
      options:
        zone: 3
        block-device: vdb
        overwrite: "true"
    ceilometer:
      branch: lp:charms/trusty/ceilometer
      constraints: mem=1G
    ceilometer-agent:
      branch: lp:charms/trusty/ceilometer-agent
    heat:
      branch: lp:charms/trusty/heat
    mongodb:
      branch: lp:charms/trusty/mongodb
      constraints: mem=1G
  relations:
    - [ keystone, mysql ]
    - [ nova-cloud-controller, mysql ]
    - [ nova-cloud-controller, rabbitmq-server ]
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute, nova-cloud-controller ]
    - [ nova-compute, mysql ]
    - - nova-compute
      - rabbitmq-server:amqp
    - [ nova-compute, glance ]
    - [ nova-compute, ceph ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ glance, ceph ]
    - [ glance, cinder ]
    - [ cinder, mysql ]
    - [ cinder, rabbitmq-server ]
    - [ cinder, nova-cloud-controller ]
    - [ cinder, keystone ]
    - [ cinder, cinder-ceph ]
    - [ cinder-ceph, ceph ]
    - [ neutron-gateway, mysql ]
    - [ neutron-gateway, nova-cloud-controller ]
    - [ openstack-dashboard, keystone ]
    - [ swift-proxy, keystone ]
    - [ swift-proxy, swift-storage-z1 ]
    - [ swift-proxy, swift-storage-z2 ]
    - [ swift-proxy, swift-storage-z3 ]
    - - ceilometer
      - keystone:identity-service
    - [ ceilometer, rabbitmq-server ]
    - [ ceilometer, mongodb ]
    - [ ceilometer-agent, nova-compute ]
    - [ ceilometer-agent, ceilometer ]
    - [ heat, mysql ]
    - [ heat, keystone ]
    - [ heat, rabbitmq-server ]
openstack-singlerabbit:
  inherits: openstack-services
  relations:
    - [ "neutron-gateway:amqp", rabbitmq-server ]
openstack-icehouse:
  inherits: openstack-singlerabbit
  services:
    neutron-api:
      branch: lp:charms/trusty/neutron-api
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: lp:charms/trusty/neutron-openvswitch
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server ]
openstack-icehouse-msg-split:
  inherits: openstack-services
  services:
    neutron-api:
      branch: lp:charms/trusty/neutron-api
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: lp:charms/trusty/neutron-openvswitch
    rabbitmq-server-neutron:
      branch: lp:charms/trusty/rabbitmq-server
      constraints: mem=1G
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server-neutron ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server-neutron ]
  - [ "neutron-gateway:amqp-nova", rabbitmq-server ]
  - [ "neutron-gateway:amqp", rabbitmq-server-neutron ]
# icehouse
precise-icehouse:
  inherits: openstack-singlerabbit
  series: precise
  overrides:
    openstack-origin: cloud:precise-icehouse
    source: cloud:precise-icehouse
precise-icehouse-proposed:
  inherits: precise-icehouse
  overrides:
    openstack-origin: cloud:precise-icehouse/proposed
    source: cloud:precise-updates/icehouse
precise-icehouse-staging:
  inherits: precise-icehouse
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/icehouse-staging
    source: ppa:ubuntu-cloud-archive/icehouse-staging
precise-icehouse-trunk:
  inherits: precise-icehouse
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/icehouse
    source: ppa:openstack-ubuntu-testing/icehouse
trusty-icehouse:
  inherits: openstack-icehouse
  series: trusty
trusty-icehouse-msg-split:
  inherits: openstack-icehouse-msg-split
  series: trusty
trusty-icehouse-proposed:
  inherits: trusty-icehouse
  overrides:
    source: proposed
    openstack-origin: distro-proposed
trusty-icehouse-trunk:
  inherits: trusty-icehouse
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/icehouse
    source: ppa:openstack-ubuntu-testing/icehouse
    offline-compression: "no"
# juno
trusty-juno:
  inherits: openstack-icehouse
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-juno
    source: cloud:trusty-juno
trusty-juno-proposed:
  inherits: trusty-juno
  overrides:
    openstack-origin: cloud:trusty-juno/proposed
    source: cloud:trusty-juno/proposed
trusty-juno-staging:
  inherits: trusty-juno
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/juno-staging
    source: ppa:ubuntu-cloud-archive/juno-staging
utopic-juno:
  inherits: openstack-icehouse
  series: utopic
utopic-juno-proposed:
  inherits: utopic-juno
  overrides:
    source: proposed
    openstack-origin: distro-proposed
# kilo
trusty-kilo:
  inherits: openstack-icehouse
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-kilo
    source: cloud:trusty-kilo
trusty-kilo-proposed:
  inherits: trusty-kilo
  overrides:
    openstack-origin: cloud:trusty-kilo/proposed
    source: cloud:trusty-kilo/proposed
trusty-kilo-staging:
  inherits: trusty-kilo
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/kilo-staging
    source: ppa:ubuntu-cloud-archive/kilo-staging
vivid-kilo:
  inherits: openstack-icehouse
  series: vivid
vivid-kilo-proposed:
  inherits: vivid-kilo
  overrides:
    source: proposed
    openstack-origin: distro-proposed
