# vim: set ts=2 et:
# Multi-hypervisor test bundle for KVM and LXD
# UOSCI relies on this for OS-on-OS deployment testing
base-services:
  services:
    mysql:
      branch: https://github.com/openstack/charm-percona-cluster;stable/17.02
      constraints: mem=4G
      options:
        max-connections: 1000
        innodb-buffer-pool-size: 512M
        root-password: ChangeMe123
        sst-password: ChangeMe123
    rabbitmq-server:
      branch: https://github.com/openstack/charm-rabbitmq-server;stable/17.02
      constraints: mem=1G
    ceph:
      branch: https://github.com/openstack/charm-ceph;stable/17.02
      num_units: 3
      constraints: mem=1G
      options:
        monitor-count: 3
        fsid: 6547bd3e-1397-11e2-82e5-53567c8d32dc
        monitor-secret: AQCXrnZQwI7KGBAAiPofmKEXKxu5bUzoYLVkbQ==
        osd-devices: /dev/vdb
        osd-reformat: "yes"
        ephemeral-unmount: /mnt
    keystone:
      branch: https://github.com/openstack/charm-keystone;stable/17.02
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      branch: https://github.com/openstack/charm-openstack-dashboard;stable/17.02
      constraints: mem=1G
    nova-compute-kvm:
      branch: https://github.com/openstack/charm-nova-compute;stable/17.02
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
    nova-compute-lxd:
      branch: https://github.com/openstack/charm-nova-compute;stable/17.02
      num_units: 3
      constraints: mem=4G
      options:
        virt-type: lxd
    lxd:
      branch: https://github.com/openstack/charm-lxd;stable/17.02
      options:
        block-devices: /dev/vdb
        ephemeral-unmount: /mnt
        storage-type: lvm
        overwrite: "true"
    nova-cloud-controller:
      branch: https://github.com/openstack/charm-nova-cloud-controller;stable/17.02
      constraints: mem=1G
      options:
        network-manager: Neutron
    neutron-gateway:
      branch: https://github.com/openstack/charm-neutron-gateway;stable/17.02
      constraints: mem=4G
      options:
        instance-mtu: 1300
        bridge-mappings: physnet1:br-ex
    cinder:
      branch: https://github.com/openstack/charm-cinder;stable/17.02
      options:
        block-device: "None"
        glance-api-version: 2
      constraints: mem=1G
    cinder-ceph:
      branch: https://github.com/openstack/charm-cinder-ceph;stable/17.02
    glance:
      branch: https://github.com/openstack/charm-glance;stable/17.02
      constraints: mem=1G
    swift-proxy:
      branch: https://github.com/openstack/charm-swift-proxy;stable/17.02
      constraints: mem=1G
      options:
        zone-assignment: manual
        replicas: 3
        swift-hash: fdfef9d4-8b06-11e2-8ac0-531c923c8fae
    swift-storage-z1:
      branch: https://github.com/openstack/charm-swift-storage;stable/17.02
      constraints: mem=1G
      options:
        zone: 1
        block-device: vdb
        overwrite: "true"
    swift-storage-z2:
      branch: https://github.com/openstack/charm-swift-storage;stable/17.02
      constraints: mem=1G
      options:
        zone: 2
        block-device: vdb
        overwrite: "true"
    swift-storage-z3:
      branch: https://github.com/openstack/charm-swift-storage;stable/17.02
      constraints: mem=1G
      options:
        zone: 3
        block-device: vdb
        overwrite: "true"
    ceilometer:
      branch: https://github.com/openstack/charm-ceilometer;stable/17.02
      constraints: mem=1G
    ceilometer-agent:
      branch: https://github.com/openstack/charm-ceilometer-agent;stable/17.02
    heat:
      branch: https://github.com/openstack/charm-heat;stable/17.02
    mongodb:
      branch: lp:charms/trusty/mongodb
      constraints: mem=1G
    neutron-api:
      branch: https://github.com/openstack/charm-neutron-api;stable/17.02
      constraints: mem=1G
      options:
        neutron-security-groups: True
        flat-network-providers: physnet1
    neutron-openvswitch:
      branch: https://github.com/openstack/charm-neutron-openvswitch;stable/17.02
  relations:
    - [ keystone, mysql ]
    - [ nova-cloud-controller, mysql ]
    - [ nova-cloud-controller, rabbitmq-server ]
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute-kvm, nova-cloud-controller ]
    - - nova-compute-kvm
      - rabbitmq-server:amqp
    - [ nova-compute-kvm, glance ]
    - [ nova-compute-kvm, ceph ]
    - [ nova-compute-lxd, nova-cloud-controller ]
    - - nova-compute-lxd
      - rabbitmq-server:amqp
    - [ nova-compute-lxd, glance ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ glance, ceph ]
    - [ glance, "cinder:image-service" ]
    - [ cinder, mysql ]
    - [ cinder, rabbitmq-server ]
    - [ cinder, nova-cloud-controller ]
    - [ cinder, keystone ]
    - [ cinder, cinder-ceph ]
    - [ cinder-ceph, ceph ]
    - [ neutron-gateway, nova-cloud-controller ]
    - [ openstack-dashboard, keystone ]
    - [ swift-proxy, keystone ]
    - [ swift-proxy, swift-storage-z1 ]
    - [ swift-proxy, swift-storage-z2 ]
    - [ swift-proxy, swift-storage-z3 ]
    - - ceilometer
      - keystone:identity-service
    - [ ceilometer, rabbitmq-server ]
    - [ ceilometer, mongodb ]
    - [ ceilometer-agent, nova-compute-kvm ]
    - [ ceilometer-agent, ceilometer ]
    - [ heat, mysql ]
    - [ heat, keystone ]
    - [ heat, rabbitmq-server ]
    - [ "neutron-gateway:amqp", rabbitmq-server ]
    - [ neutron-api, mysql ]
    - [ neutron-api, rabbitmq-server ]
    - [ neutron-api, nova-cloud-controller ]
    - [ neutron-api, neutron-openvswitch ]
    - [ neutron-api, keystone ]
    - [ neutron-api, neutron-gateway ]
    - [ neutron-openvswitch, nova-compute-kvm ]
    - [ neutron-openvswitch, nova-compute-lxd ]
    - [ neutron-openvswitch, rabbitmq-server ]
    - [ nova-compute-lxd, lxd ]
# mitaka
xenial-mitaka:
  inherits: base-services
  series: xenial
xenial-mitaka-proposed:
  inherits: xenial-mitaka
  overrides:
    source: proposed
    openstack-origin: distro-proposed
# newton
xenial-newton:
  inherits: base-services
  series: xenial
  overrides:
    openstack-origin: cloud:xenial-newton
    source: cloud:xenial-newton
    storage-type: btrfs
xenial-newton-proposed:
  inherits: xenial-newton
  overrides:
    openstack-origin: cloud:xenial-newton/proposed
    source: cloud:xenial-newton/proposed
xenial-newton-staging:
  inherits: xenial-newton
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/newton-staging
    source: ppa:ubuntu-cloud-archive/newton-staging
yakkety-newton:
  inherits: base-services
  series: yakkety
yakkety-newton-proposed:
  inherits: yakkety-newton
  overrides:
    source: proposed
    openstack-origin: distro-proposed
# ocata
xenial-ocata:
  inherits: base-services
  series: xenial
  overrides:
    openstack-origin: cloud:xenial-ocata
    source: cloud:xenial-ocata
    storage-type: btrfs
xenial-ocata-proposed:
  inherits: xenial-ocata
  overrides:
    openstack-origin: cloud:xenial-ocata/proposed
    source: cloud:xenial-ocata/proposed
xenial-ocata-staging:
  inherits: xenial-ocata
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/ocata-staging
    source: ppa:ubuntu-cloud-archive/ocata-staging
zesty-ocata:
  inherits: base-services
  series: zesty
zesty-ocata-proposed:
  inherits: zesty-ocata
  overrides:
    source: proposed
    openstack-origin: distro-proposed

