# vim: set ts=2 et:
# deployer bundle for development ('next') charms
# UOSCI relies on this for OS-on-OS deployment testing
openstack-services:
  services:
    mysql:
      branch: https://github.com/openstack/charm-percona-cluster;stable
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
#        root-password: changeme
#        sst-password: changeme
    rabbitmq-server:
      branch: https://github.com/openstack/charm-rabbitmq-server;stable
      constraints: mem=1G
    keystone:
      branch: https://github.com/openstack/charm-keystone;stable
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      branch: https://github.com/openstack/charm-openstack-dashboard;stable
      constraints: mem=1G
    nova-compute:
      branch: https://github.com/openstack/charm-nova-compute;stable
      num_units: 1
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
        virt-type: lxd
    nova-cloud-controller:
      branch: https://github.com/openstack/charm-nova-cloud-controller;stable
      constraints: mem=1G
      options:
        network-manager: Neutron
        quantum-security-groups: "yes"
    neutron-gateway:
      branch: https://github.com/openstack/charm-neutron-gateway;stable
      constraints: mem=1G
      options:
        instance-mtu: 1300
    glance:
      branch: https://github.com/openstack/charm-glance;stable
      constraints: mem=1G
    lxd:
      branch: 
      options: https://github.com/openstack/charm-lxd
        block-device: /mnt/disk.img|20G
        storage-type: btrfs
  relations:
    - [ keystone, mysql ]
    - [ nova-cloud-controller, mysql ]
    - [ nova-cloud-controller, rabbitmq-server ]
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute, nova-cloud-controller ]
    - [ nova-compute, mysql ]
    - [ nova-compute, lxd ]
    - - nova-compute
      - rabbitmq-server:amqp
    - [ nova-compute, glance ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ neutron-gateway, nova-cloud-controller ]
    - [ openstack-dashboard, keystone ]
openstack-singlerabbit:
  inherits: openstack-services
  relations:
    - [ "neutron-gateway:amqp", rabbitmq-server ]
openstack-icehouse:
  inherits: openstack-singlerabbit
  services:
    neutron-api:
      branch: https://github.com/openstack/charm-neutron-api
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: https://github.com/openstack/charm-neutron-openvswitch
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server ]
openstack-icehouse-msg-split:
  inherits: openstack-services
  services:
    neutron-api:
      branch: https://github.com/openstack/charm-neutron-api
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: https://github.com/openstack/charm-neutron-openvswitch
    rabbitmq-server-neutron:
      branch: https://github.com/openstack/charm-rabbitmq-server;stable
      constraints: mem=1G
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server-neutron ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server-neutron ]
  - [ "neutron-gateway:amqp-nova", rabbitmq-server ]
  - [ "neutron-gateway:amqp", rabbitmq-server-neutron ]
# icehouse
openstack-icehouse-git:
  inherits: openstack-icehouse
  services:
    keystone:
      options:
        openstack-origin-git: include-file://keystone-icehouse.yaml
    glance:
      options:
        openstack-origin-git: include-file://glance-icehouse.yaml
    neutron-api:
      options:
        openstack-origin-git: include-file://neutron-icehouse.yaml
    neutron-gateway:
      options:
        openstack-origin-git: include-file://neutron-icehouse.yaml
    neutron-openvswitch:
      options:
        openstack-origin-git: include-file://neutron-icehouse.yaml
    openstack-dashboard:
      options:
        openstack-origin-git: include-file://horizon-icehouse.yaml
    nova-compute:
      options:
        openstack-origin-git: include-file://nova-icehouse.yaml
    nova-cloud-controller:
      options:
        openstack-origin-git: include-file://nova-icehouse.yaml
precise-icehouse:
  inherits: openstack-icehouse-git
  series: precise
  services:
    mysql:
      branch: lp:charms/trusty/mysql
  overrides:
    openstack-origin: cloud:precise-icehouse
    source: cloud:precise-icehouse
trusty-icehouse:
  inherits: openstack-icehouse-git
  series: trusty
# juno
openstack-juno-git:
  inherits: openstack-icehouse
  services:
    keystone:
      options:
        openstack-origin-git: include-file://keystone-juno.yaml
    glance:
      options:
        openstack-origin-git: include-file://glance-juno.yaml
    neutron-api:
      options:
        openstack-origin-git: include-file://neutron-juno.yaml
    neutron-gateway:
      options:
        openstack-origin-git: include-file://neutron-juno.yaml
    neutron-openvswitch:
      options:
        openstack-origin-git: include-file://neutron-juno.yaml
    openstack-dashboard:
      options:
        openstack-origin-git: include-file://horizon-juno.yaml
    nova-compute:
      options:
        openstack-origin-git: include-file://nova-juno.yaml
    nova-cloud-controller:
      options:
        openstack-origin-git: include-file://nova-juno.yaml
trusty-juno:
  inherits: openstack-juno-git
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-juno
    source: cloud:trusty-juno
utopic-juno:
  inherits: openstack-juno-git
  series: utopic
# liberty
openstack-liberty-git:
  inherits: openstack-icehouse
  services:
    keystone:
      options:
        openstack-origin-git: include-file://keystone-liberty.yaml
    glance:
      options:
        openstack-origin-git: include-file://glance-liberty.yaml
    neutron-api:
      options:
        openstack-origin-git: include-file://neutron-liberty.yaml
    neutron-gateway:
      options:
        openstack-origin-git: include-file://neutron-liberty.yaml
    neutron-openvswitch:
      options:
        openstack-origin-git: include-file://neutron-liberty.yaml
    openstack-dashboard:
      options:
        openstack-origin-git: include-file://horizon-liberty.yaml
    nova-compute:
      options:
        openstack-origin-git: include-file://nova-liberty.yaml
    nova-cloud-controller:
      options:
        openstack-origin-git: include-file://nova-liberty.yaml
trusty-liberty:
  inherits: openstack-liberty-git
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-liberty
    source: cloud:trusty-liberty
trusty-liberty-proposed:
  inherits: openstack-liberty-git
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-liberty/proposed
    source: cloud:trusty-liberty/proposed
wily-liberty:
  inherits: openstack-liberty-git
  series: wily
  services:
    mysql:
      branch: lp:charms/trusty/mysql
# master
openstack-master-git:
  inherits: openstack-icehouse
  services:
    keystone:
      options:
        openstack-origin-git: include-file://keystone-master.yaml
    glance:
      options:
        openstack-origin-git: include-file://glance-master.yaml
    neutron-api:
      options:
        openstack-origin-git: include-file://neutron-master.yaml
    neutron-gateway:
      options:
        openstack-origin-git: include-file://neutron-master.yaml
    neutron-openvswitch:
      options:
        openstack-origin-git: include-file://neutron-master.yaml
    openstack-dashboard:
      options:
        openstack-origin-git: include-file://horizon-master.yaml
    nova-compute:
      options:
        openstack-origin-git: include-file://nova-master.yaml
    nova-cloud-controller:
      options:
        openstack-origin-git: include-file://nova-master.yaml
trusty-master:
  inherits: openstack-master-git
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-mitaka
    source: cloud:trusty-mitaka
trusty-master-proposed:
  inherits: openstack-master-git
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-mitaka/proposed
    source: cloud:trusty-mitaka/proposed
xenial-master:
  inherits: openstack-master-git
  series: xenial
  services:
    mysql:
      branch: lp:charms/trusty/mysql
