# vim: set ts=2 et:
# deployer bundle for development ('next') charms
# UOSCI relies on this for OS-on-OS deployment testing
openstack-services:
  services:
    mysql:
      branch: lp:~openstack-charmers/charms/trusty/percona-cluster/next
      constraints: mem=1G
      options:
        dataset-size: 50%
    rabbitmq-server:
      branch: lp:~openstack-charmers/charms/trusty/rabbitmq-server/next
      constraints: mem=1G
    ceph:
      branch: lp:~openstack-charmers/charms/trusty/ceph/next
      num_units: 3
      constraints: mem=1G
      options:
        monitor-count: 3
        fsid: 6547bd3e-1397-11e2-82e5-53567c8d32dc
        monitor-secret: AQCXrnZQwI7KGBAAiPofmKEXKxu5bUzoYLVkbQ==
        osd-devices: /dev/vdb
        osd-reformat: "yes"
        ephemeral-unmount: /mnt
    keystone:
      branch: lp:~openstack-charmers/charms/trusty/keystone/next
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      branch: lp:~openstack-charmers/charms/trusty/openstack-dashboard/next
      constraints: mem=1G
    nova-compute:
      branch: lp:~openstack-charmers/charms/trusty/nova-compute/lxd-updates
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
        virt-type: lxd
    nova-cloud-controller:
      branch: lp:~openstack-charmers/charms/trusty/nova-cloud-controller/next
      constraints: mem=1G
      options:
        network-manager: Neutron
        quantum-security-groups: "yes"
    neutron-gateway:
      branch: lp:~openstack-charmers/charms/trusty/neutron-gateway/next
      constraints: mem=1G
      options:
        instance-mtu: 1300
    cinder:
      branch: lp:~openstack-charmers/charms/trusty/cinder/next
      options:
        block-device: "None"
        glance-api-version: 2
      constraints: mem=1G
    cinder-ceph:
      branch: lp:~openstack-charmers/charms/trusty/cinder-ceph/next
    glance:
      branch: lp:~openstack-charmers/charms/trusty/glance/next
      constraints: mem=1G
    swift-proxy:
      branch: lp:~openstack-charmers/charms/trusty/swift-proxy/next
      constraints: mem=1G
      options:
        zone-assignment: manual
        replicas: 3
        swift-hash: fdfef9d4-8b06-11e2-8ac0-531c923c8fae
    swift-storage-z1:
      branch: lp:~openstack-charmers/charms/trusty/swift-storage/next
      constraints: mem=1G
      options:
        zone: 1
        block-device: vdb
        overwrite: "true"
    swift-storage-z2:
      branch: lp:~openstack-charmers/charms/trusty/swift-storage/next
      constraints: mem=1G
      options:
        zone: 2
        block-device: vdb
        overwrite: "true"
    swift-storage-z3:
      branch: lp:~openstack-charmers/charms/trusty/swift-storage/next
      constraints: mem=1G
      options:
        zone: 3
        block-device: vdb
        overwrite: "true"
    ceilometer:
      branch: lp:~openstack-charmers/charms/trusty/ceilometer/next
      constraints: mem=1G
    ceilometer-agent:
      branch: lp:~openstack-charmers/charms/trusty/ceilometer-agent/next
    heat:
      branch: lp:~openstack-charmers/charms/trusty/heat/next
    mongodb:
      branch: lp:charms/trusty/mongodb
      constraints: mem=1G
    lxd:
      branch: lp:~openstack-charmers/charms/trusty/lxd/next
      options:
        lxd-block-device: /mnt/disk.img|20G
        #lxd-origin: ppa:ubuntu-lxc/lxd-git-master
        lxd-trust-password: changeme
  relations:
    - [ keystone, mysql ]
    - [ nova-cloud-controller, mysql ]
    - [ nova-cloud-controller, rabbitmq-server ]
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute, nova-cloud-controller ]
    - [ nova-compute, lxd ]
    - [ nova-compute, mysql ]
    - - nova-compute
      - rabbitmq-server:amqp
    - [ nova-compute, glance ]
    - [ nova-compute, ceph ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ glance, ceph ]
    - [ glance, cinder ]
    - [ cinder, mysql ]
    - [ cinder, rabbitmq-server ]
    - [ cinder, nova-cloud-controller ]
    - [ cinder, keystone ]
    - [ cinder, cinder-ceph ]
    - [ cinder-ceph, ceph ]
    - [ neutron-gateway, mysql ]
    - [ neutron-gateway, nova-cloud-controller ]
    - [ openstack-dashboard, keystone ]
    - [ swift-proxy, keystone ]
    - [ swift-proxy, swift-storage-z1 ]
    - [ swift-proxy, swift-storage-z2 ]
    - [ swift-proxy, swift-storage-z3 ]
    - - ceilometer
      - keystone:identity-service
    - [ ceilometer, rabbitmq-server ]
    - [ ceilometer, mongodb ]
    - [ ceilometer-agent, nova-compute ]
    - [ ceilometer-agent, ceilometer ]
    - [ heat, mysql ]
    - [ heat, keystone ]
    - [ heat, rabbitmq-server ]
openstack-singlerabbit:
  inherits: openstack-services
  relations:
    - [ "neutron-gateway:amqp", rabbitmq-server ]
openstack-icehouse:
  inherits: openstack-singlerabbit
  services:
    neutron-api:
      branch: lp:~openstack-charmers/charms/trusty/neutron-api/next
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: lp:~openstack-charmers/charms/trusty/neutron-openvswitch/next
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server ]
openstack-icehouse-msg-split:
  inherits: openstack-services
  services:
    neutron-api:
      branch: lp:~openstack-charmers/charms/trusty/neutron-api/next
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: lp:~openstack-charmers/charms/trusty/neutron-openvswitch/next
    rabbitmq-server-neutron:
      branch: lp:charms/trusty/rabbitmq-server
      constraints: mem=1G
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server-neutron ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server-neutron ]
  - [ "neutron-gateway:amqp-nova", rabbitmq-server ]
  - [ "neutron-gateway:amqp", rabbitmq-server-neutron ]
# kilo
trusty-kilo:
  inherits: openstack-icehouse
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-kilo
    source: cloud:trusty-kilo
trusty-kilo-proposed:
  inherits: trusty-kilo
  overrides:
    openstack-origin: cloud:trusty-kilo/proposed
    source: cloud:trusty-kilo/proposed
trusty-kilo-staging:
  inherits: trusty-kilo
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/kilo-staging
    source: ppa:ubuntu-cloud-archive/kilo-staging
vivid-kilo:
  inherits: openstack-icehouse
  series: vivid
  services:
    mysql:
      branch: lp:charms/trusty/mysql
vivid-kilo-proposed:
  inherits: vivid-kilo
  overrides:
    source: proposed
    openstack-origin: distro-proposed
# liberty
trusty-liberty:
  inherits: openstack-icehouse
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-liberty
    source: cloud:trusty-liberty
trusty-liberty-proposed:
  inherits: trusty-liberty
  overrides:
    openstack-origin: cloud:trusty-liberty/proposed
    source: cloud:trusty-liberty/proposed
trusty-liberty-staging:
  inherits: trusty-liberty
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/liberty-staging
    source: ppa:ubuntu-cloud-archive/liberty-staging
wily-liberty:
  inherits: openstack-icehouse
  series: wily
  services:
    mysql:
      branch: lp:charms/trusty/mysql
wily-liberty-proposed:
  inherits: wily-liberty
  overrides:
    source: proposed
    openstack-origin: distro-proposed
