# vim: set ts=2 et:
# deployer bundle for development ('next') charms
# UOSCI relies on this for OS-on-OS deployment testing
openstack-services:
  services:
    mysql:
      branch: lp:charms/trusty/mysql
      constraints: mem=1G
      options:
        dataset-size: 50%
        max-connections: 20000
    rabbitmq-server:
      branch: lp:~openstack-charmers/charms/trusty/rabbitmq-server/next
      constraints: mem=1G
    keystone:
      branch: lp:~openstack-charmers/charms/trusty/keystone/next
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      branch: lp:~openstack-charmers/charms/trusty/openstack-dashboard/next
      constraints: mem=1G
    nova-compute:
      branch: lp:~openstack-charmers/charms/trusty/nova-compute/lxd-updates
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
        virt-type: lxd
    nova-cloud-controller:
      branch: lp:~openstack-charmers/charms/trusty/nova-cloud-controller/next
      constraints: mem=1G
      options:
        network-manager: Neutron
        quantum-security-groups: "yes"
    neutron-gateway:
      branch: lp:~james-page/charms/trusty/neutron-gateway/liberty-fixup
      constraints: mem=1G
      options:
        instance-mtu: 1300
    glance:
      branch: lp:~openstack-charmers/charms/trusty/glance/next
      constraints: mem=1G
    swift-proxy:
      branch: lp:~openstack-charmers/charms/trusty/swift-proxy/next
      constraints: mem=1G
      options:
        zone-assignment: manual
        replicas: 3
        swift-hash: fdfef9d4-8b06-11e2-8ac0-531c923c8fae
    swift-storage-z1:
      branch: lp:~openstack-charmers/charms/trusty/swift-storage/next
      constraints: mem=1G
      options:
        zone: 1
        block-device: vdb
        overwrite: "true"
    swift-storage-z2:
      branch: lp:~openstack-charmers/charms/trusty/swift-storage/next
      constraints: mem=1G
      options:
        zone: 2
        block-device: vdb
        overwrite: "true"
    swift-storage-z3:
      branch: lp:~openstack-charmers/charms/trusty/swift-storage/next
      constraints: mem=1G
      options:
        zone: 3
        block-device: vdb
        overwrite: "true"
    lxd:
      branch: lp:~openstack-charmers/charms/trusty/lxd/next
      options:
        block-device: /dev/vdb
        trust-password: changeme
        ephemeral-unmount: /mnt
        storage-type: lvm
        use-source: True
  relations:
    - [ keystone, mysql ]
    - [ nova-cloud-controller, mysql ]
    - [ nova-cloud-controller, rabbitmq-server ]
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute, nova-cloud-controller ]
    - [ nova-compute, lxd ]
    - [ nova-compute, mysql ]
    - - nova-compute
      - rabbitmq-server:amqp
    - [ nova-compute, glance ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ glance, swift-proxy ]
    - [ neutron-gateway, mysql ]
    - [ neutron-gateway, nova-cloud-controller ]
    - [ openstack-dashboard, keystone ]
    - [ swift-proxy, keystone ]
    - [ swift-proxy, swift-storage-z1 ]
    - [ swift-proxy, swift-storage-z2 ]
    - [ swift-proxy, swift-storage-z3 ]
openstack-singlerabbit:
  inherits: openstack-services
  relations:
    - [ "neutron-gateway:amqp", rabbitmq-server ]
openstack-icehouse:
  inherits: openstack-singlerabbit
  services:
    neutron-api:
      branch: lp:~openstack-charmers/charms/trusty/neutron-api/next
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: lp:~openstack-charmers/charms/trusty/neutron-openvswitch/next
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server ]
openstack-icehouse-msg-split:
  inherits: openstack-services
  services:
    neutron-api:
      branch: lp:~openstack-charmers/charms/trusty/neutron-api/next
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: lp:~openstack-charmers/charms/trusty/neutron-openvswitch/next
    rabbitmq-server-neutron:
      branch: lp:charms/trusty/rabbitmq-server
      constraints: mem=1G
  relations:
  - [ neutron-api, mysql ]
  - [ neutron-api, rabbitmq-server-neutron ]
  - [ neutron-api, nova-cloud-controller ]
  - [ neutron-api, neutron-openvswitch ]
  - [ neutron-api, keystone ]
  - [ neutron-api, neutron-gateway ]
  - [ neutron-openvswitch, nova-compute ]
  - [ neutron-openvswitch, rabbitmq-server-neutron ]
  - [ "neutron-gateway:amqp-nova", rabbitmq-server ]
  - [ "neutron-gateway:amqp", rabbitmq-server-neutron ]
# kilo
trusty-kilo:
  inherits: openstack-icehouse
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-kilo
    source: cloud:trusty-kilo
trusty-kilo-proposed:
  inherits: trusty-kilo
  overrides:
    openstack-origin: cloud:trusty-kilo/proposed
    source: cloud:trusty-kilo/proposed
trusty-kilo-staging:
  inherits: trusty-kilo
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/kilo-staging
    source: ppa:ubuntu-cloud-archive/kilo-staging
vivid-kilo:
  inherits: openstack-icehouse
  series: vivid
  services:
    mysql:
      branch: lp:charms/trusty/mysql
vivid-kilo-proposed:
  inherits: vivid-kilo
  overrides:
    source: proposed
    openstack-origin: distro-proposed
# liberty
trusty-liberty:
  inherits: openstack-icehouse
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-liberty
    source: cloud:trusty-liberty
trusty-liberty-proposed:
  inherits: trusty-liberty
  overrides:
    openstack-origin: cloud:trusty-liberty/proposed
    source: cloud:trusty-liberty/proposed
trusty-liberty-staging:
  inherits: trusty-liberty
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/liberty-staging
    source: ppa:ubuntu-cloud-archive/liberty-staging
wily-liberty:
  inherits: openstack-icehouse
  series: wily
  services:
    mysql:
      branch: lp:charms/trusty/mysql
wily-liberty-proposed:
  inherits: wily-liberty
  overrides:
    source: proposed
    openstack-origin: distro-proposed
