# vim: set ts=2 et:
# deployer bundle for stable charms
# UOSCI relies on this for OS-on-OS deployment testing
base-services:
  services:
    rabbitmq-server:
      branch: https://github.com/openstack/charm-rabbitmq-server;stable/16.07
      constraints: mem=1G
    keystone:
      branch: https://github.com/openstack/charm-keystone;stable/16.07
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      branch: https://github.com/openstack/charm-openstack-dashboard;stable/16.07
      constraints: mem=1G
    nova-compute:
      branch: https://github.com/openstack/charm-nova-compute;stable/16.07
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
        virt-type: lxd
    nova-cloud-controller:
      branch: https://github.com/openstack/charm-nova-cloud-controller;stable/16.07
      constraints: mem=1G
      options:
        network-manager: Neutron
    neutron-gateway:
      branch: https://github.com/openstack/charm-neutron-gateway;stable/16.07
      constraints: mem=1G
      options:
        instance-mtu: 1300
    neutron-api:
      branch: https://github.com/openstack/charm-neutron-api;stable/16.07
      constraints: mem=1G
      options:
        neutron-security-groups: True
    neutron-openvswitch:
      branch: https://github.com/openstack/charm-neutron-openvswitch;stable/16.07
    glance:
      branch: https://github.com/openstack/charm-glance;stable/16.07
      constraints: mem=1G
    swift-proxy:
      branch: https://github.com/openstack/charm-swift-proxy;stable/16.07
      constraints: mem=1G
      options:
        zone-assignment: manual
        replicas: 3
        swift-hash: fdfef9d4-8b06-11e2-8ac0-531c923c8fae
    swift-storage-z1:
      branch: https://github.com/openstack/charm-swift-storage;stable/16.07
      constraints: mem=1G
      options:
        zone: 1
        block-device: vdb
        overwrite: "true"
    swift-storage-z2:
      branch: https://github.com/openstack/charm-swift-storage;stable/16.07
      constraints: mem=1G
      options:
        zone: 2
        block-device: vdb
        overwrite: "true"
    swift-storage-z3:
      branch: https://github.com/openstack/charm-swift-storage;stable/16.07
      constraints: mem=1G
      options:
        zone: 3
        block-device: vdb
        overwrite: "true"
    ceilometer:
      branch: https://github.com/openstack/charm-ceilometer;stable/16.07
      constraints: mem=1G
    ceilometer-agent:
      branch: https://github.com/openstack/charm-ceilometer-agent;stable/16.07
    heat:
      branch: https://github.com/openstack/charm-heat;stable/16.07
    mongodb:
      branch: lp:charms/trusty/mongodb
      constraints: mem=1G
    lxd:
      branch: https://github.com/openstack/charm-lxd
      options:
        block-devices: /dev/vdb
        ephemeral-unmount: /mnt
        storage-type: zfs
        overwrite: "true"
  relations:
    - [ keystone, mysql ]
    - [ nova-cloud-controller, mysql ]
    - [ nova-cloud-controller, rabbitmq-server ]
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute, nova-cloud-controller ]
    - [ nova-compute, mysql ]
    - [ nova-compute, lxd ]
    - - nova-compute
      - rabbitmq-server:amqp
    - [ nova-compute, glance ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ glance, rabbitmq-server ]
    - [ neutron-gateway, nova-cloud-controller ]
    - [ openstack-dashboard, keystone ]
    - [ swift-proxy, keystone ]
    - [ swift-proxy, swift-storage-z1 ]
    - [ swift-proxy, swift-storage-z2 ]
    - [ swift-proxy, swift-storage-z3 ]
    - - ceilometer
      - keystone:identity-service
    - [ ceilometer, rabbitmq-server ]
    - [ ceilometer, mongodb ]
    - [ ceilometer-agent, nova-compute ]
    - [ ceilometer-agent, ceilometer ]
    - [ heat, mysql ]
    - [ heat, keystone ]
    - [ heat, rabbitmq-server ]
    - [ "neutron-gateway:amqp", rabbitmq-server ]
    - [ neutron-api, mysql ]
    - [ neutron-api, rabbitmq-server ]
    - [ neutron-api, nova-cloud-controller ]
    - [ neutron-api, neutron-openvswitch ]
    - [ neutron-api, keystone ]
    - [ neutron-api, neutron-gateway ]
    - [ neutron-openvswitch, nova-compute ]
    - [ neutron-openvswitch, rabbitmq-server ]
openstack-services-legacy:
  inherits: base-services
  services:
    mysql:
      branch: lp:charms/trusty/mysql
      constraints: mem=2G
      options:
        dataset-size: 50%
        max-connections: 20000
openstack-services:
  inherits: base-services
  services:
    mysql:
      branch: https://github.com/openstack/charm-percona-cluster;stable/16.07
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
# mitaka
xenial-mitaka:
  inherits: openstack-services
  series: xenial
xenial-mitaka-proposed:
  inherits: xenial-mitaka
  overrides:
    source: proposed
    openstack-origin: distro-proposed
